### ISSUE TITLE
fix(front): search delay and bug of image with dot name

### ISSUE THREAD

**Issue by ntorga** [goinfinite/ez-issue-tracker#85]
If you try to search an image name that has a dot, the search won't appear cause it thinks it's a domain. Try with "rocket.chat".
The search also has a long delay, so you have to wait like 2 to 3 seconds until the dropdown shows up.

**Comment by polillomm** [comment]
I had to implement a timeout to prevent it from entering a search loop for each letter typed. I reduced the execution waiting time from **3000 ms** to **500 ms**, which I believe is more than sufficient to accommodate the user's typing speed.

Additionally, I modified the image input validation to ensure it checks for a complete URL, as specified in the task, rather than just verifying if it contains a domain or the HTTP/HTTPS scheme.
